config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :places

  resources :hotels

  devise_for :users

  get 'welcomes/welcome'
 get "show_map"=> "welcomes#show_map"
  root 'welcomes#welcome'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'signout', to: 'sessions#destroy', via: [:get , :post]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
	has_many :plases , dependent: :destroy
end

app/models/place.rb
class Place < ActiveRecord::Base
	belongs_to :hotel
end

app/models/twitter_user.rb
class TwitterUser < ActiveRecord::Base

	def self.from_omniauth(auth)
		where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
	end

	def self.create_from_omniauth(auth)
		create! do |user|
			user.provider = auth["provider"]
			user.uid = auth["uid"]
			user.name = auth["info"]["nickname"]
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   include SimpleCaptcha::ControllerHelpers
  protect_from_forgery with: :exception
   def after_sign_in_path_for(resource)
    "/show_map"
  end

  protected
    
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password) }
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit( :email, :password, :password_confirmation, :captcha, :captcha_key) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit( :email, :password, :password_confirmation, :current_password) }
    end
private
	
	def current_user
		@current_user ||= TwitterUser.find(session[:t_user_id]) if session[:t_user_id]
	end
	helper_method :current_user
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @hotels = Hotel.all
    respond_with(@hotels)
  end

  def show
    respond_with(@hotel)
  end

  def new
    @hotel = Hotel.new
    respond_with(@hotel)
  end

  def edit
  end

  def create
    @hotel = Hotel.new(hotel_params)
    @hotel.save
    respond_with(@hotel)
  end

  def update
    @hotel.update(hotel_params)
    respond_with(@hotel)
  end

  def destroy
    @hotel.destroy
    respond_with(@hotel)
  end

  private
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    def hotel_params
      params.require(:hotel).permit(:name)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @places = Place.all
    respond_with(@places)
  end

  def show
    respond_with(@place)
  end

  def new
    @place = Place.new
    respond_with(@place)
  end

  def edit
  end

  def create
    @place = Place.new(place_params)
    @place.save
    respond_with(@place)
  end

  def update
    @place.update(place_params)
    respond_with(@place)
  end

  def destroy
    @place.destroy
    respond_with(@place)
  end

  private
    def set_place
      @place = Place.find(params[:id])
    end

    def place_params
      params.require(:place).permit(:city, :image, :hotel_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		t_user = TwitterUser.from_omniauth(auth_hash)
		session[:t_user_id] = t_user.id
		redirect_to show_map_path, notice: "You have successfully Signed In"
	end

	def destroy
		session[:t_user_id] = nil
		redirect_to root_path, notice: "You have successfully Signed Out"
	end
  protected

  def auth_hash
   ActionController::Parameters.new(request.env["omniauth.auth"]).permit(:provider, :uid, info: [:nickname])
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
	require 'open-uri'
	#before_filter :authenticate_admin!,:only=>[:show_map]
  def welcome
  end
  def show_map
  	puts current_admin.inspect
  	ip=request.remote_ip #for server
  	#ip="14.194.252.77" #for local
  	url=URI.encode("http://ip-api.com/json/"+ip)
  	open(url) do |http|
	  @response = http.read
	  puts "response: #{@response}"
	end
	@hash=JSON.parse @response.gsub('=>', ':')
	puts @hash.inspect
	puts @response.to_json
	if @hash["countryCode"]=="IN"
		@cities=["Mumbai","Pune","Dilhi","Kolhapur"]
	else
		@cities=["US"]
	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/hotels/_form.html.erb
<%= form_for(@hotel) do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<h1>Listing hotels</h1>
<!-- Single button -->
<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    Restaurants <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><a href="#">McDonalds</a></li>
    <li class="divider"></li>
    <li><a href="#">SuperMacs</a></li>
  </ul>
</div>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %></td>
        <td><%= link_to 'Show', hotel %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel', new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>

app/views/layouts/_bootstrap.html.erb
 	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

app/views/layouts/_footer.html.erb
Copyrights : Apoorv Purohit, NCI

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Restaurant</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/about">About</a></li>
        <li><a href="/pages/contact">Contact</a></li>
      </ul>
       <ul class="nav navbar-nav navbar-right">
      <% if current_admin %>
     
       <li> Signed in as <%= current_admin.email %></li>
       <li><%= link_to "Go For Restaurants", "/show_map" %></li> 
      <li><%= link_to "Sign Out",  destroy_admin_session_path, :method => :delete %></li>
            
        <% elsif current_user %>
          <ul class="nav navbar-nav navbar-right">
       <li> Signed in as <%= current_user.name %></li>
       <li><%= link_to "Go For Restaurants", "/show_map" %></li>
       <li> <%= link_to "Sign Out", signout_path %></li></ul>    
      <% else %>
       <li><%= link_to "Sign In", new_admin_session_path %></li>     

        <li><%= link_to "Registration", new_admin_registration_path %></li>
     <li><%= link_to "Login With Twitter", "/auth/twitter" %></li>
      <% end %>

      
      <%# end %>

        
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 <%= render 'layouts/bootstrap' %>
</head>
<body>
	 <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  <div class="container-fluid">
     	<%= yield %>
     
     <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :hotel_id %><br>
    <%= f.number_field :hotel_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Image</th>
      <th>Hotel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.city %></td>
        <td><%= place.image %></td>
        <td><%= place.hotel_id %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @place.city %>
</p>

<p>
  <strong>Image:</strong>
  <%= @place.image %>
</p>

<p>
  <strong>Hotel:</strong>
  <%= @place.hotel_id %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/simple_captcha/_simple_captcha.erb
<style type="text/css">
  .simple_captcha{border: 1px solid #ccc; padding: 5px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 110px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 16px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>

  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>

  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>

  <div class='simple_captcha_refresh_button'>
    <%= simple_captcha_options[:refresh_button] %>
  </div>
</div>

app/views/welcomes/show_map.html.erb
<%= @hash["city"] %><%= request.remote_ip %>
<style>
      html, body, #map-canvas {
        height: 500px;
        margin: 0px;
        padding: 0px
      }
      .display
      {
      	display: none;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script>
function initialize() {
  var myLatlng = new google.maps.LatLng(<%= @hash["lat"] %>,<%= @hash["lon"] %>);
  var mapOptions = {
    zoom: 4,
    center: myLatlng
  }
  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

  var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: 'Hello World!'
  });
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
<div id="map-canvas" class="pull-left col-md-6"></div>
<div  class="pull-right col-md-6">
	<div id="type"><%= select_tag "selec_type", options_for_select([ ["Mcdonald's","Mcdonald's"], ["supermacs","supermacs" ]]), prompt: "Select something", :onchange=>"show_bellow();" %></div>


   <div class="prodselectbox">
    <div class="floatleft cat">Country</div>
    <div class="floatleft catid">
        <select id="selectcat" name="categoryselected" onchange="show_bellow();">
            <option value="" class="rhth">Select Country</option>
            <option class="edibles" value="Edible Oils" id="selectionone">Ireland</option>
            <option class="vegfats" value="Vegetable Cooking Fats" id="selectiontwo">Japan</option>
            <option class='bak' value="Baking" id="selectionfive">China</option>
           
        </select>
    </div>


    <div class="floatleft artid">City</div>
    <div class="floatleft selectarticle"  id="city">
        <select id="selectprod" name="articleID" onchange="show_image();">
            <option value="" class="rhth23">Select City</option>
            <option value="elianto" class="selectors edibles" >Dublin</option>
            <option value="ufuta" class="selectors edibles" >Cork</option>
            <option value="bahari-fry" class="selectors edibles">Galway</option>
            
            <option value="chipo-pus-3" class="selectors vegfats">Biejing</option>
            <option value="cowboy" class="selectors vegfats">Taipei</option>
            <option value="kimbo" class="selectors vegfats">Shangai</option>
           
            <option value="pure-natural-active-man" class="selectors percare">Pure & Natural Active-Man</option>
            <option value="pure-natural-beauty-soap" class="selectors percare">Pure & Natural Beauty Soap</option>
            <option value="biddy" class="selectors marga">Biddy&#39;s</option>
            <option value="gold-band-margarine" class="selectors marga">Gold Band Margarine</option>
            <option value="veebol-pastry" class="selectors marga">Veebool Pastry</option>
            <option value="bake-rite" class="selectors bak">Beijing</option>
            <option value="mariandazi" class="selectors bak">Taipei</option>
            <option value="mariandazi" class="selectors bak">Shangai</option>
            
        </select>
    </div>






	<div class="display" id="image" ><img id="display_image"  width="500px" src="/assets/city/Kolhapur.jpg"></div>
	<div class="display" id="button" class="bs-example" style="margin-top:20px">
    <div class="btn-group" data-toggle="buttons">
        <label class="btn btn-primary">
            <input type="checkbox">  101
        </label>
        <label class="btn btn-primary">
            <input type="checkbox">  102
        </label>
        <label class="btn btn-primary">
            <input type="checkbox">  103
        </label>
        <label class="btn btn-primary">
            <input type="checkbox">  104
        </label>
        <label class="btn btn-primary">
            <input type="checkbox">  105
        </label>
        <label class="btn btn-primary">
            <input type="checkbox">  106
        </label>
        <label class="btn btn-primary">
            <input type="checkbox">  107
        </label>
        <label class="btn btn-primary">
            <input type="checkbox">  108
        </label>
        <label class="btn btn-primary">
            <input type="checkbox">  109
        </label>
        <label class="btn btn-primary">
            <input type="checkbox">  110
        </label>
    </div>
    <div class="col-md-12" style="margin-top:20px">
       <%= show_simple_captcha %>
    <button onclick="redirect_page()" type="button" class="btn btn-default">Submit</button></div>
</div>
</div>
<script type="text/javascript">
function show_image()
{
	document.getElementById("display_image").src='/assets/city/Dilhi.jpg'
	// $("#image").innerhtml='<img width="500px" src="/assets/city/'+$("#select_city").val()+'.jpg">';

	$("#image")[0].style.display="block";
	$("#button")[0].style.display="block";
	
}
function redirect_page()
{
  alert(" Booking is done  ");
  window.location.assign("/");
}
	function show_bellow()
	{
	
		$("#city")[0].style.display="block";
		$("#image")[0].style.display="none";
		$("#button")[0].style.display="none";

	
}
$(document).ready(function () {    
    var allOptions = $('#selectprod option')
    $('#selectcat').change(function () {
        $('#selectprod option').remove()
        var classN = $('#selectcat option:selected').prop('class');
        var opts = allOptions.filter('.' + classN);
        $.each(opts, function (i, j) {
            $(j).appendTo('#selectprod');
        });
    });
});
</script>

app/views/welcomes/welcome.html.erb
<h1>Welcome</h1>
<p> An online application to book restaurant tables </p>